project_name = "flexflow"
testsuite_macro = "FF_TEST_SUITE"
namespace_name = "FlexFlow"
header_extension = ".h"

build_targets = [
  "utils",
  "op-attrs",
  "kernels",
  "substitutions",
  "compiler",
  "kernel-tests",
]

test_targets = [
  "kernel-tests",
]

[cmake_flags_extra]
FF_CUDA_ARCH = "60"
CMAKE_CUDA_ARCHITECTURES = "60"
